name: branch

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build with dotnet
      run: dotnet build -c Release
    - name: Run unit tests
      run: dotnet test
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MathConverter
        path: MathConverter\bin\Release\*nupkg
