name: build-wpf

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.0.x
          3.1.x
          6.0.x
    - name: Build with dotnet
      working-directory: ./MathConverter/WPF
      run: dotnet build -c Release
    - name: Build test project
      working-directory: ./MathConverter.UnitTests/WPF
      run: dotnet build
    - name: Run unit tests
      working-directory: ./MathConverter.UnitTests/WPF
      run: dotnet test
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MathConverter
        path: MathConverter\WPF\bin\Release\*nupkg
