name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/Buerkert/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet build -c Release --version-suffix build.${{ github.run_number }}
    - name: Run unit tests
      run: dotnet test
    - name: Push generated package to GitHub registry
      run: dotnet nuget push MathConverter\bin\Release\Buerkert.MathConverter.*.nupkg --skip-duplicate
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MathConverter
        path: MathConverter\bin\Release\*nupkg
